name: main
on:
  workflow_dispatch:
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  statuses: write
  pull-requests: write
  repository-projects: write
  security-events: write
  id-token: write
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: trstringer,acdunnigan
      - name: Deploy to production
        run: echo deploying
