name: main

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: execute py script
        id: code
        run: |
          python my_file.py "${{ secrets.TOKEN }}" "TerraformDestroyPLan"
          Output=$(python -c "
         
          with open("GitHub_Output.txt") as file_1:
              file_1_content = [line.strip() for line in file_1.readlines()]
              print(file_1_content[0])
          
          ")
          echo "TEST=$Output" >> $GITHUB_OUTPUT
      - name: print env
        run: echo "${{ steps.code.outputs.TEST }}"
