name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: print ls
        run: | 
          ls
      - name: execute py script # run file
        run: |
          python my_file.py Abdul
      - name: Deploy to production
        run: echo deploying
 
