name: main
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: print ls
        run: | 
          ls
      - name: execute py script # run file
        run: |
          Output=$(python my_file.py Abdul kahadar)
          echo "TEST=$Output" >> $GITHUB_OUTPUT
      - name: print env
        run: echo "$GITHUB_OUTPUT"
 
