name: "manipulate TeamTokens"

on:
  workflow_dispatch:
    inputs:
      Team:
        required: true
        default: 'Platform_Team'

jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    outputs:
      TF_API_TOKEN: ${{ steps.tf_team_token.outputs.TF_API_TOKEN }}
    steps:
      - name: set team token
        id: tf_team_token
        run: echo "export TF_API_TOKEN=${{ secrets.TF_API_TOKEN }}" >> $GITHUB_ENV

  job2:
    needs: TeamTokens
    runs-on: ubuntu-latest
    steps:
     - name: get env
       run: echo ${{ needs.TeamTokens.outputs.TF_API_TOKEN }}
      
