name: "manipulate TeamTokens"
on:
  push:
   branches:
    - main

jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    outputs:
      secret-value: ${{ steps.check.outputs.secret_value }}
    steps:
      - name: set team token
        id: tf_team_token
        run: |
          echo "::set-output name=secret_value::${{ secrets.TF_API_TOKEN }}"
		 
  job2:
    needs: TeamTokens
    uses: BrazilAmazon/terraform_poc/.github/workflows/terraformpoc.yml@main
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_HOSTNAME: ${{ vars.TF_CLOUD_HOSTNAME }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    secrets:
      TF_API_TOKEN: ${{ needs.TeamTokens.outputs.secret-value }}
