name: manipulate TeamTokens
on:
  workflow_dispatch:
    inputs:
      Team: 
          type: choice
          required: true
          description: choose Team to RUN
          options:
          - Platform_Team
          - Dev_Team
      Destroy:
          type: choice
          required: true
          description: choose To Destroy
          options:
          - destroymodule
          - tfstate
      

jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    steps:
      - name: set team token
        id: tf_team_token
        run: |
          echo "Hello-world"
  Platform_Team:
    needs: TeamTokens
    uses: BrazilAmazon/terraform_poc/.github/workflows/terraformpoc.yml@main
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_HOSTNAME: ${{ vars.TF_CLOUD_HOSTNAME }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    secrets:
      TF_API_TOKEN: ${{ inputs.Team == 'Platform_Team' &&  secrets.TF_API_TOKEN || inputs.Team == 'Dev_Team' &&  secrets.TF_API_TOKEN_DEV_TEAM || inputs.Team == 'System_Team' &&  secrets.TF_API_TOKEN_SYSTEM_TEAM }}
      Tf_Destroy: ${{ inputs.Destroy }}
