name: manupulate TeamTokens
on:
  workflow_dispatch:
    inputs:
      Team:
        required: true
        type: string
		
jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    environment: env
    outputs:
      TF_API_TOKEN: ${{ steps.tf_team_token.outputs.TF_API_TOKEN }}
    steps:
      - name: set team token
        id: tf_team_token
        run: |
          echo "export TF_API_TOKEN=${{ secrets.TF_API_TOKEN }}" >> $GITHUB_ENV
		 
  job2:
    needs: TeamTokens
    uses: BrazilAmazon/terraform_poc/.github/workflows/terraformpoc.yml@main
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_HOSTNAME: ${{ vars.TF_CLOUD_HOSTNAME }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    secrets:
      TF_API_TOKEN: ${{ needs.TeamTokens.outputs.TF_API_TOKEN }}

