name: manipulate TeamTokens
on:
  workflow_dispatch:
    inputs:
      Team:
        required: true
        type: string
		
jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    steps:
      - name: set team token
        id: tf_team_token
        run: |
          echo "Hello-world"
		 
  job2:
    needs: TeamTokens
    uses: BrazilAmazon/terraform_poc/.github/workflows/terraformpoc.yml@main
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_HOSTNAME: ${{ vars.TF_CLOUD_HOSTNAME }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
      TF_TEAM: ${{ inputs.Team }}
