name: "manipulate TeamTokens"

on:
  workflow_dispatch:
    inputs:
      Team:
        required: true
        default: 'Platform_Team'

jobs:
  TeamTokens:
    runs-on: ubuntu-latest
    outputs:
      TF_CLOUD_HOSTNAME: ${{ steps.tf_team_token.outputs.TF_CLOUD_HOSTNAME }}
    steps:
      - name: set team token
        id: tf_team_token
        run: echo "TF_CLOUD_HOSTNAME=${{ vars.TF_CLOUD_HOSTNAME || 'true' }}" >> $GITHUB_ENV

  job2:
    needs: TeamTokens
    uses: BrazilAmazon/terraform_poc/.github/workflows/terraformpoc.yml@main
    with:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_HOSTNAME: ${{ needs.TeamTokens.outputs.TF_CLOUD_HOSTNAME }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
