name: "Terraform Plan"

on:
  workflow_dispatch

env:
  TF_CLOUD_ORGANIZATION : ${{ vars.Tf_Cloud_Organization }}
  TF_CLOUD_HOSTNAME : ${{ vars.TF_CLOUD_HOSTNAME }}
  TF_WORKSPACE : ${{ vars.TF_WORKSPACE }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
 # ARM_CLIENT_ID:  ${{ vars.ARM_CLIENT_ID }}
 # ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 # ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
 # ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: print token
        run: echo $TF_TOKEN_app_terraform_io
      - name: Checkout
        uses: actions/checkout@v3
   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: $TF_TOKEN_app_terraform_io

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: |
            echo "------------------------------------------"
            export exitcode=0
            autotfvars=()
            for file in $(ls $environment/); do
                if [[ "$file" == *auto.tfvars ]]; then
                    autotfvars+=($PWD/$environment/$file)
                fi
            done
            echo "==============================="
            echo ${autotfvars[0]}
            echo ${autotfvars[*]}
            echo $PWD
            echo "+++++++++++++++++++++++++++++"
            if [[ "${#autotfvars[@]}" -gt 1 ]] ; then
                    terraform plan -var-file=<(cat ${autotfvars[*]}) -no-color -out tfplan || export exitcode=$?
            		echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                    
                    if [ $exitcode -eq 1 ]; then
                      echo Terraform Plan Failed!
                      exit 1
                    else 
                      exit 0
                    fi
            else
                    terraform plan -var-file=<(cat ${autotfvars[0]}) -no-color -out tfplan || export exitcode=$?
            		echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                    
                    if [ $exitcode -eq 1 ]; then
                      echo Terraform Plan Failed!
                      exit 1
                    else 
                      exit 0
                    fi
            fi
      - name: Terraform apply
        run: terraform apply "tfplan"
