name: "Terraform"

on:
  workflow_dispatch

env:
  environment : ${{ vars.environment }}
  TF_CLOUD_ORGANIZATION : ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_CLOUD_HOSTNAME : ${{ vars.TF_CLOUD_HOSTNAME }}
  TF_WORKSPACE : ${{ vars.TF_WORKSPACE }}
 # TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
  ARM_CLIENT_ID:  ${{ vars.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

permissions:
  actions: read
jobs:
 terraform:
   name: "Terraform plan"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: .
 
   steps:
      - run: export TF_TOKEN_app_terraform_io=${{ secrets.TF_API_TOKEN }}
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
 
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
           
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: |
            export exitcode=0
            autotfvars=()
            
            for file in $(ls $environment/); do
                if [[ "$file" == *auto.tfvars ]]; then
                    autotfvars+=($file)
                fi
            done
            
            if [[ "${#autotfvars[@]}" -gt 1 ]] ; then
                    terraform plan -var-file=<(cat ${autotfvars[*]}) -detailed-exitcode -no-color -out tfplan || export exitcode=$?
            		echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                    
                    if [ $exitcode -eq 1 ]; then
                      echo Terraform Plan Failed!
                      exit 1
                    else 
                      exit 0
                    fi
            else
                    terraform plan -var-file=<(cat ${autotfvars[0]}) -detailed-exitcode -no-color -out tfplan || export exitcode=$?
            		echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                    
                    if [ $exitcode -eq 1 ]; then
                      echo Terraform Plan Failed!
                      exit 1
                    else 
                      exit 0
                    fi
            fi
